version: '3'
services:
  web-app:
    build:
      context: .
    container_name: hakus_rails_app
    volumes:
      - ./:/myapp
      - node_modules_volume:/myapp/node_modules
    ports:
      - 9651:3000
    working_dir: "/myapp"
    tty: true
    depends_on:
      - web-db
  web-db:
    image: mysql:8.0
    container_name: hakus_rails_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web-app-db
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9652:3306
    tty: true
    volumes:
      - web-db:/var/lib/mysql
volumes:
  web-db:
    name: hakus-rails-db
  node_modules_volume:
    name: hakus-rails-webpack-node-modules
